spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:

        #       show_sql: true
        format_sql: true
upload:
  directory: C:/directory/upload